### ISSUE TITLE
Models defined with id property and defaultFn fail in version 5.5.0

### ISSUE THREAD

**Issue by jamesjjk** [loopbackio/loopback-connector-mongodb#608]
## Steps to reproduce

Define an ID property with a defaultFn such as shortId

```
"id": {
      "id": true,
      "type": "string",
      "defaultFn": "shortid",
      "required": true,
      "description": "Short Id is automatically generated"
    }
```

## Current Behavior

ShortId is no longer automatically generated on an Model.upsertWithWhere call. Validation will fail if the id property is required.

## Expected Behavior

ShortId should be automatically generated on an Model.upsertWithWhere call. Validation must pass as the ID should ideally already exist

## Additional information

- Validated working in version v5.4.0
- Broken in version v5.5.0
- [ ] Consider replacing shortid function with nanoid. (shortid is deprecated).

**Comment by dhmlau** [comment]
@hacksparrow, could you please take a look? Thanks.

**Comment by jannyHou** [comment]
Hey @jamesjjk is `created` method also affected? Or only `upsertWithWhere`?

**Comment by jamesjjk** [comment]
@jannyHou I cannot verify this at this moment in time, assuming that upsertWithWhere is not atomic in release v5.5.0, then created would be effected too.

**Comment by jannyHou** [comment]
@jamesjjk @bajtos I did some investigation with PR [juggler#1884](https://github.com/strongloop/loopback-datasource-juggler/pull/1884) and https://github.com/strongloop/loopback-connector-mongodb/pull/609, am afraid with the atomic `upsertWithWhere` fully implemented and controlled by mongodb connector, you have to call `find` then `create` to apply loopback level's default functions. Here is the reason:

In the old version, `upsertWithWhere` knows when to apply the default values because it calls `find` first:
- if found return, 
- if not, then **apply default values** and call `create`

The logic above is fully controlled by juggler, see [related code](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L847-L856)

But with the atomic `upsertWithWhere` fully controlled by the mongodb connector, it calls mogodb database's [`findOneOrCreate`](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L1735) to process the data, neither juggler nor the connector has a chance to interfere in the middle, therefore loopback doesn't have the chance to apply default values(Please note applying default values is a loopback model construct level's behaviour, database has no way to understand how to do it).

**Comment by jannyHou** [comment]
Sorry that I didn't realize it's a breaking change when review the PR. A solution I could think of is, introducing an option flag to disable the atomic upsertWithWhere, e.g. `Todo.upsertWithWhere(where, data, {disableAtomic})`, to make it fall back to the previous behaviour, then document this. WDYT?

**Comment by jannyHou** [comment]
cc @mrbatista You may also want to join the discussion :)

**Comment by bajtos** [comment]
I checked MongoDB's documentation for `findOneOrCreate` [here](https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndUpdate/) and AFAICT, there is no way how to specify values to apply to new records only (i.e. the default values).

I think that means our users have two options:
1. Use the current atomic implementation but don't have default values applied
2. Use the previous find+create implementation that fills default values but is vulnerable to race conditions

I like the idea to introduce an option to control the behavior. IMO, a method-level option is not very practical, I prefer to start with datasource-level one. Ideally, we should have datasource-level, model-level and method-level option, but that can be implemented later.

I am proposing the following plan:
1. Introduce a new setting `atomicUpsertWithWhere`, this setting should enable the new feature and should be turned off by default for backwards compatibility. This change should be back-ported to `5.x` branch.
2. For the upcoming `6.0` release, we should land a change to `master` that will change that default to enable the atomic variant by default.

It would be great to have tests to verify both cases (atomic upsertWithWhere enabled or disabled), but I guess I can live with one set of tests for the default behavior only (disabled in 5.x, enabled in 6.x).

Thoughts?

**Comment by jamesjjk** [comment]
@bajtos thoughts from a users perspective:

I think you are referring to findOneAndUpdate: https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndUpdate/ ?

However would it not be great to be able to inject the defaults using setOnInsert https://docs.mongodb.com/manual/reference/operator/update/setOnInsert/index.html incase of an upsert case (i.e. upsert: true?

This way you maintain an fully atomic operation with defaults.

**Comment by bajtos** [comment]
Thank you @jamesjjk for the comment. I am not familiar with MongoDB, so I was not aware there is `setOnInsert` operator. If this operator can be used together with `findOneAndUpdate`, then I agree with you that our connector should leverage that mechanism to provide fully atomic operations with defaults.

Would you like to submit a pull request to contribute that change? Here is the code building the MongoDB command:

https://github.com/strongloop/loopback-connector-mongodb/blob/7393fc5983dcddbe99a9b499e00b86f87a48e8b4/lib/mongodb.js#L1733-L1742

While adding support for default values to `upsertWithWhere`, you may consider applying the same fix for other related methods, for example `updateOrCreate`:

https://github.com/strongloop/loopback-connector-mongodb/blob/7393fc5983dcddbe99a9b499e00b86f87a48e8b4/lib/mongodb.js#L823-L834
